README.md
packages/forge/README.md

add shields to display build status and package version
move plugin usage docs into plugin README

docs: update README

---

packages/forge/README.md

add prerequisites section to plugin README
add instructions on how to update baseHref for Custom UI
fix Custom UI manifest.yml example

docs: update plugin README

---

packages/forge/src/generators/application/files/tsconfig.app.json

fix(build): remove baseUrl redefinition

---

.github/workflows/ci.yml

fix an issue whereby checking out a forked repository fails

fix(ci): fix PR CI config

---

package-lock.json
package.json
packages/forge/README.md
packages/forge/package.json
packages/forge/src/executors/build/executor.ts
packages/forge/src/executors/build/lib/compile-webpack.ts
packages/forge/src/executors/build/lib/copy-forge-app-assets.ts

fix Forge app build to use Node Webpack build to bundle project dependencies
Closes: #11

fix(build): fix Forge app build to bundle dependencies

---

.releaserc
CONTRIBUTING.md

add semantic release config to allow pre-releasing any branch

build(ci): add feature prerelease config

---

package-lock.json
package.json
packages/forge/src/executors/build/executor.ts
packages/forge/src/executors/build/lib/load-manifest-yml.ts
packages/forge/src/executors/build/lib/patch-manifest-yml.ts
packages/forge/src/executors/build/lib/process-custom-ui-dependencies.ts

Update Forge manifest dependency to make sure we accept the latest manifest schema

feat: update Forge manifest dependency

---

e2e/forge-e2e/tests/forge.spec.ts
packages/forge/src/executors/build/executor.ts

fix Forge app build to ensure the project graph exist before trying to read it. If it does not exist rebuild it because the cache location may have changed
Closes: #21

fix: fix(build): fix Forge app build to assure project graph exists

---

packages/forge/package.json

fix peer dependencies in Forge plugin package.json to match required Nx major version
Closes: #27

fix: fix peer deps in plugin package.json

---

package-lock.json
package.json
packages/forge/package.json

feat(nx): migrate to Nx 15.3.3

---

packages/nx-forge/README.md

add schema reference links to executor documentation

docs: add schema reference

---

packages/nx-forge/package.json

fix: fix deps in plugin package.json

---

e2e/nx-forge-e2e/tests/build.executor.spec.ts
packages/nx-forge/src/executors/build/executor.ts

fix: update build executor to skip webpack build if source is absent

---

docs/guides/examples.md

BREAKING CHANGE: requires Nx 18
Closes #66

feat(nx): update to Nx 18

---

docs/reference/executors.md
packages/nx-forge/src/executors/build/lib/normalize-options.ts
packages/nx-forge/src/executors/build/lib/process-custom-ui-dependencies.ts
packages/nx-forge/src/executors/build/schema.d.ts
packages/nx-forge/src/executors/build/schema.json
packages/nx-forge/src/executors/package/executor.ts
packages/nx-forge/src/executors/package/schema.d.ts
packages/nx-forge/src/executors/package/schema.json

fix(executors): fix issue with inferred build targets

---

docs/.vitepress/config.mts
docs/guides/adding-a-custom-ui-module.md
docs/guides/adding-a-ui-kit-2-module.md
docs/guides/getting-started.md
docs/reference/executors.md
packages/nx-forge/src/executors/build/executor.ts
packages/nx-forge/src/executors/build/lib/patch-manifest-yml.ts
packages/nx-forge/src/executors/build/lib/process-resource-dependencies.ts
packages/nx-forge/src/executors/build/schema.d.ts
packages/nx-forge/src/executors/build/schema.json
packages/nx-forge/src/executors/package/executor.ts
packages/nx-forge/src/executors/package/schema.d.ts
packages/nx-forge/src/executors/package/schema.json

feat(executors): support UI Kit 2

---

.github/workflows/ci-main.yml
.github/workflows/ci-pr.yml
.github/workflows/release.yml
docs/.vitepress/config.mts
docs/guides/transforming-the-manifest.md
docs/reference/executors.md
package-lock.json
package.json
packages/nx-forge/package.json
packages/nx-forge/src/executors/deploy/executor.ts
packages/nx-forge/src/executors/deploy/lib/transform-manifest-yml.ts
packages/nx-forge/src/executors/deploy/schema.d.ts
packages/nx-forge/src/executors/deploy/schema.json
packages/nx-forge/src/utils/forge/manifest-yml.ts

feat(executors): support manifest transforms

---

docs/reference/executors.md
packages/nx-forge/src/executors/deploy/schema.d.ts
packages/nx-forge/src/executors/deploy/schema.json
packages/nx-forge/src/executors/install/schema.d.ts
packages/nx-forge/src/executors/install/schema.json

fix(executors): allow any environment name

---

docs/guides/getting-started.md

add build target dependency step
Fixes: #104

docs: update getting stared guide

---

docs/guides/adding-a-custom-ui-module.md
docs/guides/adding-a-ui-kit-2-module.md
docs/guides/getting-started.md
docs/package-lock.json
docs/package.json

update docs to Nx 19
Closes #112

feat(nx): update to Nx 19

---

packages/nx-forge/src/generators/init/generator.ts
packages/nx-forge/src/generators/init/schema.d.ts
packages/nx-forge/src/generators/init/schema.json
packages/nx-forge/src/utils/versions.ts

add init generator options to skip package.json updates or keep existing package versions
Closes #118

fix(generators): update init generator to set @forge package version

---

docs/reference/executors.md
packages/nx-forge/src/executors/install/schema.d.ts
packages/nx-forge/src/executors/install/schema.json

update the install executor to support the bitbucket product option
Closes #123

feat(executors): support bitbucket product option

---

.github/workflows/ci-pr.yml
package-lock.json
package.json
packages/nx-forge/package.json
packages/nx-forge/src/generators/application/files/manifest.yml

update @forge/manifest to version 8.1.0 supporting the latest manifest runtime values
Closes #134

build(deps): update Forge package dependencies

---

docs/guides/adding-a-custom-ui-module.md
docs/guides/getting-started.md
docs/reference/generators.md

docs: updates for Nx 20 compatibility

---

docs/.vitepress/config.mts
docs/concepts/motivation.md
docs/concepts/workspace-layout.md
docs/guides/adding-a-ui-kit-module.md
docs/reference/executors.md
packages/nx-forge/.eslintrc.json
packages/nx-forge/src/executors/build/lib/patch-manifest-yml.ts
packages/nx-forge/src/executors/build/lib/process-resource-dependencies.ts
packages/nx-forge/src/executors/build/schema.json
packages/nx-forge/src/executors/package/schema.json
packages/nx-forge/src/executors/tunnel/executor.ts
packages/nx-forge/src/executors/tunnel/lib/extract-custom-ui-projects.ts
packages/nx-forge/src/executors/tunnel/lib/run-tunnel.ts
packages/nx-forge/src/executors/tunnel/lib/start-custom-uis.ts
packages/nx-forge/src/executors/tunnel/schema.d.ts
packages/nx-forge/src/executors/tunnel/schema.json
packages/nx-forge/src/generators/application/files/webpack.config.js__tmpl__
packages/nx-forge/src/graph/create-dependencies.ts
packages/nx-forge/src/graph/create-nodes.ts
packages/nx-forge/src/migrations/update-2-3-0/remove-implicit-custom-ui-dependencies.spec.ts
packages/nx-forge/src/migrations/update-2-3-0/remove-implicit-custom-ui-dependencies.ts
packages/nx-forge/src/shared/manifest/util-manifest.spec.ts
packages/nx-forge/src/shared/manifest/util-manifest.ts
packages/nx-forge/src/shared/targets/get-tunnel-config.ts
packages/nx-forge/src/utils/forge/manifest-yml.ts
tsconfig.base.json

fix executor implementation;run package task before tunneling; fix target naming from serve to tunnel everywhere;refactor code to infer resource types and distinguish between custom-ui, ui-kit and generic resources
Closes #133

fix: tunnel executor

---

packages/nx-forge/src/executors/install/executor.ts
packages/nx-forge/src/executors/install/schema.d.ts
packages/nx-forge/src/executors/install/schema.json

add x-prompt options for site and product options (strangely they don't seem to work)
Closes #46

fix: add install license option

---

packages/nx-forge/src/executors/package/lib/generate-package-json.ts

fix: remove unexpected this. reference

---

docs/reference/executors.md
packages/nx-forge/src/executors/package/schema.json
packages/nx-forge/src/executors/tunnel/executor.ts
packages/nx-forge/src/executors/tunnel/lib/extract-custom-ui-projects.ts
packages/nx-forge/src/executors/tunnel/lib/extract-ui-kit-projects.ts
packages/nx-forge/src/executors/tunnel/lib/start-ui-kit-project-builds.ts

feat: tunnel UI Kit apps

---

packages/nx-forge/src/executors/build/lib/copy-forge-app-assets.ts
packages/nx-forge/src/executors/build/lib/process-resource-dependencies.ts
packages/nx-forge/src/generators/application/files/README.md
packages/nx-forge/src/utils/util-fs.ts

delete resource project output path before copying new resource files
Closes #164

feat: delete resource project output path on package

---

package-lock.json
package.json
packages/nx-forge/package.json

update @forge/manifest to version 10.3.0 supporting the latest manifest schema and axios with security patch
Closes #172

fix(deps): update Forge package dependencies
